name: Cypress Allure Report CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Cypress tests with Allure enabled
      - name: Run Cypress tests
        run: npx cypress run --env allure=true --spec "cypress/e2e/test1.cy.js"

      # 5️⃣ Generate Allure report
      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      # 6️⃣ Upload Allure report as artifact
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # 7️⃣ Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
