name: Cypress Allure Report CI

on:
  workflow_dispatch:       # manual trigger
  push:
    branches: [main]      # optional, run on push to main

jobs:
  run-specific-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run specific Cypress test file
      - name: Run Cypress Test
        run: npx cypress run --spec "cypress/e2e/test1.cy.js"

      # 5️⃣ Generate Allure Report
      - name: Generate Allure Report
        run: npx allure generate cypress/allure-results --clean -o cypress/allure-report

      # 6️⃣ Upload Allure Report as Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: cypress/allure-report

      # 7️⃣ Upload Screenshots (optional)
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # 8️⃣ Upload Videos (optional)
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos